// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: FileServer.proto

package server

import (
	"context"

	"XcStorage/XcXcPanFileServer"
	"XcStorage/internal/logic"
	"XcStorage/internal/svc"
)

type XcXcPanFileServiceServer struct {
	svcCtx *svc.ServiceContext
	XcXcPanFileServer.UnimplementedXcXcPanFileServiceServer
}

func NewXcXcPanFileServiceServer(svcCtx *svc.ServiceContext) *XcXcPanFileServiceServer {
	return &XcXcPanFileServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *XcXcPanFileServiceServer) UploadChunk(ctx context.Context, in *XcXcPanFileServer.UploadChunkRequest) (*XcXcPanFileServer.UploadChunkResponse, error) {
	l := logic.NewUploadChunkLogic(ctx, s.svcCtx)
	return l.UploadChunk(in)
}

func (s *XcXcPanFileServiceServer) DelChunk(ctx context.Context, in *XcXcPanFileServer.DelChunkRequest) (*XcXcPanFileServer.DelChunkResponse, error) {
	l := logic.NewDelChunkLogic(ctx, s.svcCtx)
	return l.DelChunk(in)
}

func (s *XcXcPanFileServiceServer) DownloadChunk(ctx context.Context, in *XcXcPanFileServer.DownloadChunkRequest) (*XcXcPanFileServer.DownloadChunkResponse, error) {
	l := logic.NewDownloadChunkLogic(ctx, s.svcCtx)
	return l.DownloadChunk(in)
}
